# Generated by Django 5.1.2 on 2024-11-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(max_length=300),
        ),
    ]
