# Generated by Django 5.1.2 on 2024-11-19 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_publicaciones_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
