# Generated by Django 5.1.2 on 2024-11-19 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_publicaciones_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2024, 11, 19, 1, 48, 27, 718036, tzinfo=datetime.timezone.utc)),
        ),
    ]
