# Generated by Django 5.1.2 on 2024-11-19 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_publicaciones_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 1, 50, 0, 725229, tzinfo=datetime.timezone.utc)),
        ),
    ]
