# Generated by Django 5.1.2 on 2024-11-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_publicaciones_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(max_length=600),
        ),
    ]
